// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using zadanie4.Data;

#nullable disable

namespace zadanie4.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260313101851_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("zadanie4.Models.Odpowiedz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PunktyCialo")
                        .HasColumnType("int");

                    b.Property<int>("PunktyDuchowosc")
                        .HasColumnType("int");

                    b.Property<int>("PunktyPraca")
                        .HasColumnType("int");

                    b.Property<int>("PunktyRelacje")
                        .HasColumnType("int");

                    b.Property<int>("PunktyUmysl")
                        .HasColumnType("int");

                    b.Property<int>("PytanieId")
                        .HasColumnType("int");

                    b.Property<string>("Tresc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PytanieId");

                    b.ToTable("Odpowiedzi");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PunktyCialo = 0,
                            PunktyDuchowosc = 0,
                            PunktyPraca = 0,
                            PunktyRelacje = 0,
                            PunktyUmysl = 10,
                            PytanieId = 1,
                            Tresc = "Czytam / uczę się czegoś"
                        },
                        new
                        {
                            Id = 2,
                            PunktyCialo = 0,
                            PunktyDuchowosc = 0,
                            PunktyPraca = 0,
                            PunktyRelacje = 0,
                            PunktyUmysl = 5,
                            PytanieId = 1,
                            Tresc = "Oglądam coś"
                        },
                        new
                        {
                            Id = 3,
                            PunktyCialo = 0,
                            PunktyDuchowosc = 3,
                            PunktyPraca = 0,
                            PunktyRelacje = 0,
                            PunktyUmysl = 7,
                            PytanieId = 1,
                            Tresc = "Tworzę coś (rysunek, pisanie itp.)"
                        },
                        new
                        {
                            Id = 4,
                            PunktyCialo = 0,
                            PunktyDuchowosc = 0,
                            PunktyPraca = 0,
                            PunktyRelacje = 10,
                            PunktyUmysl = 0,
                            PytanieId = 1,
                            Tresc = "Spotykam się z kimś"
                        },
                        new
                        {
                            Id = 5,
                            PunktyCialo = 10,
                            PunktyDuchowosc = 0,
                            PunktyPraca = 0,
                            PunktyRelacje = 0,
                            PunktyUmysl = 0,
                            PytanieId = 1,
                            Tresc = "Sport / ruch"
                        },
                        new
                        {
                            Id = 6,
                            PunktyCialo = 2,
                            PunktyDuchowosc = 0,
                            PunktyPraca = 0,
                            PunktyRelacje = 0,
                            PunktyUmysl = 0,
                            PytanieId = 2,
                            Tresc = "1"
                        },
                        new
                        {
                            Id = 7,
                            PunktyCialo = 4,
                            PunktyDuchowosc = 0,
                            PunktyPraca = 0,
                            PunktyRelacje = 0,
                            PunktyUmysl = 0,
                            PytanieId = 2,
                            Tresc = "2"
                        },
                        new
                        {
                            Id = 8,
                            PunktyCialo = 6,
                            PunktyDuchowosc = 0,
                            PunktyPraca = 0,
                            PunktyRelacje = 0,
                            PunktyUmysl = 0,
                            PytanieId = 2,
                            Tresc = "3"
                        },
                        new
                        {
                            Id = 9,
                            PunktyCialo = 8,
                            PunktyDuchowosc = 0,
                            PunktyPraca = 0,
                            PunktyRelacje = 0,
                            PunktyUmysl = 0,
                            PytanieId = 2,
                            Tresc = "4"
                        },
                        new
                        {
                            Id = 10,
                            PunktyCialo = 10,
                            PunktyDuchowosc = 0,
                            PunktyPraca = 0,
                            PunktyRelacje = 0,
                            PunktyUmysl = 0,
                            PytanieId = 2,
                            Tresc = "5"
                        },
                        new
                        {
                            Id = 11,
                            PunktyCialo = 0,
                            PunktyDuchowosc = 0,
                            PunktyPraca = 0,
                            PunktyRelacje = 0,
                            PunktyUmysl = 2,
                            PytanieId = 3,
                            Tresc = "1"
                        },
                        new
                        {
                            Id = 12,
                            PunktyCialo = 0,
                            PunktyDuchowosc = 0,
                            PunktyPraca = 0,
                            PunktyRelacje = 0,
                            PunktyUmysl = 4,
                            PytanieId = 3,
                            Tresc = "2"
                        },
                        new
                        {
                            Id = 13,
                            PunktyCialo = 0,
                            PunktyDuchowosc = 0,
                            PunktyPraca = 0,
                            PunktyRelacje = 0,
                            PunktyUmysl = 6,
                            PytanieId = 3,
                            Tresc = "3"
                        },
                        new
                        {
                            Id = 14,
                            PunktyCialo = 0,
                            PunktyDuchowosc = 0,
                            PunktyPraca = 0,
                            PunktyRelacje = 0,
                            PunktyUmysl = 8,
                            PytanieId = 3,
                            Tresc = "4"
                        },
                        new
                        {
                            Id = 15,
                            PunktyCialo = 0,
                            PunktyDuchowosc = 0,
                            PunktyPraca = 0,
                            PunktyRelacje = 0,
                            PunktyUmysl = 10,
                            PytanieId = 3,
                            Tresc = "5"
                        },
                        new
                        {
                            Id = 16,
                            PunktyCialo = 0,
                            PunktyDuchowosc = 0,
                            PunktyPraca = 10,
                            PunktyRelacje = 0,
                            PunktyUmysl = 0,
                            PytanieId = 4,
                            Tresc = "Osiąganie celów"
                        },
                        new
                        {
                            Id = 17,
                            PunktyCialo = 0,
                            PunktyDuchowosc = 3,
                            PunktyPraca = 0,
                            PunktyRelacje = 0,
                            PunktyUmysl = 7,
                            PytanieId = 4,
                            Tresc = "Kreatywność"
                        },
                        new
                        {
                            Id = 18,
                            PunktyCialo = 0,
                            PunktyDuchowosc = 0,
                            PunktyPraca = 0,
                            PunktyRelacje = 10,
                            PunktyUmysl = 0,
                            PytanieId = 4,
                            Tresc = "Pomaganie innym"
                        },
                        new
                        {
                            Id = 19,
                            PunktyCialo = 5,
                            PunktyDuchowosc = 0,
                            PunktyPraca = 0,
                            PunktyRelacje = 0,
                            PunktyUmysl = 5,
                            PytanieId = 4,
                            Tresc = "Przygoda i nowe doświadczenia"
                        },
                        new
                        {
                            Id = 20,
                            PunktyCialo = 0,
                            PunktyDuchowosc = 10,
                            PunktyPraca = 0,
                            PunktyRelacje = 0,
                            PunktyUmysl = 0,
                            PytanieId = 4,
                            Tresc = "Spokój i stabilność"
                        },
                        new
                        {
                            Id = 21,
                            PunktyCialo = 0,
                            PunktyDuchowosc = 0,
                            PunktyPraca = 0,
                            PunktyRelacje = 2,
                            PunktyUmysl = 0,
                            PytanieId = 5,
                            Tresc = "1"
                        },
                        new
                        {
                            Id = 22,
                            PunktyCialo = 0,
                            PunktyDuchowosc = 0,
                            PunktyPraca = 0,
                            PunktyRelacje = 4,
                            PunktyUmysl = 0,
                            PytanieId = 5,
                            Tresc = "2"
                        },
                        new
                        {
                            Id = 23,
                            PunktyCialo = 0,
                            PunktyDuchowosc = 0,
                            PunktyPraca = 0,
                            PunktyRelacje = 6,
                            PunktyUmysl = 0,
                            PytanieId = 5,
                            Tresc = "3"
                        },
                        new
                        {
                            Id = 24,
                            PunktyCialo = 0,
                            PunktyDuchowosc = 0,
                            PunktyPraca = 0,
                            PunktyRelacje = 8,
                            PunktyUmysl = 0,
                            PytanieId = 5,
                            Tresc = "4"
                        },
                        new
                        {
                            Id = 25,
                            PunktyCialo = 0,
                            PunktyDuchowosc = 0,
                            PunktyPraca = 0,
                            PunktyRelacje = 10,
                            PunktyUmysl = 0,
                            PytanieId = 5,
                            Tresc = "5"
                        },
                        new
                        {
                            Id = 26,
                            PunktyCialo = 0,
                            PunktyDuchowosc = 0,
                            PunktyPraca = 0,
                            PunktyRelacje = 0,
                            PunktyUmysl = 10,
                            PytanieId = 6,
                            Tresc = "Analizuję i szukam rozwiązania"
                        },
                        new
                        {
                            Id = 27,
                            PunktyCialo = 0,
                            PunktyDuchowosc = 0,
                            PunktyPraca = 0,
                            PunktyRelacje = 8,
                            PunktyUmysl = 0,
                            PytanieId = 6,
                            Tresc = "Pytam kogoś o radę"
                        },
                        new
                        {
                            Id = 28,
                            PunktyCialo = 5,
                            PunktyDuchowosc = 0,
                            PunktyPraca = 5,
                            PunktyRelacje = 0,
                            PunktyUmysl = 0,
                            PytanieId = 6,
                            Tresc = "Działam od razu i testuję"
                        },
                        new
                        {
                            Id = 29,
                            PunktyCialo = 0,
                            PunktyDuchowosc = 8,
                            PunktyPraca = 0,
                            PunktyRelacje = 0,
                            PunktyUmysl = 0,
                            PytanieId = 6,
                            Tresc = "Robię przerwę i wracam później"
                        },
                        new
                        {
                            Id = 30,
                            PunktyCialo = 2,
                            PunktyDuchowosc = 0,
                            PunktyPraca = 0,
                            PunktyRelacje = 0,
                            PunktyUmysl = 0,
                            PytanieId = 7,
                            Tresc = "1"
                        },
                        new
                        {
                            Id = 31,
                            PunktyCialo = 4,
                            PunktyDuchowosc = 0,
                            PunktyPraca = 0,
                            PunktyRelacje = 0,
                            PunktyUmysl = 0,
                            PytanieId = 7,
                            Tresc = "2"
                        },
                        new
                        {
                            Id = 32,
                            PunktyCialo = 6,
                            PunktyDuchowosc = 0,
                            PunktyPraca = 0,
                            PunktyRelacje = 0,
                            PunktyUmysl = 0,
                            PytanieId = 7,
                            Tresc = "3"
                        },
                        new
                        {
                            Id = 33,
                            PunktyCialo = 8,
                            PunktyDuchowosc = 0,
                            PunktyPraca = 0,
                            PunktyRelacje = 0,
                            PunktyUmysl = 0,
                            PytanieId = 7,
                            Tresc = "4"
                        },
                        new
                        {
                            Id = 34,
                            PunktyCialo = 10,
                            PunktyDuchowosc = 0,
                            PunktyPraca = 0,
                            PunktyRelacje = 0,
                            PunktyUmysl = 0,
                            PytanieId = 7,
                            Tresc = "5"
                        },
                        new
                        {
                            Id = 35,
                            PunktyCialo = 0,
                            PunktyDuchowosc = 2,
                            PunktyPraca = 0,
                            PunktyRelacje = 0,
                            PunktyUmysl = 0,
                            PytanieId = 8,
                            Tresc = "1"
                        },
                        new
                        {
                            Id = 36,
                            PunktyCialo = 0,
                            PunktyDuchowosc = 4,
                            PunktyPraca = 0,
                            PunktyRelacje = 0,
                            PunktyUmysl = 0,
                            PytanieId = 8,
                            Tresc = "2"
                        },
                        new
                        {
                            Id = 37,
                            PunktyCialo = 0,
                            PunktyDuchowosc = 6,
                            PunktyPraca = 0,
                            PunktyRelacje = 0,
                            PunktyUmysl = 0,
                            PytanieId = 8,
                            Tresc = "3"
                        },
                        new
                        {
                            Id = 38,
                            PunktyCialo = 0,
                            PunktyDuchowosc = 8,
                            PunktyPraca = 0,
                            PunktyRelacje = 0,
                            PunktyUmysl = 0,
                            PytanieId = 8,
                            Tresc = "4"
                        },
                        new
                        {
                            Id = 39,
                            PunktyCialo = 0,
                            PunktyDuchowosc = 10,
                            PunktyPraca = 0,
                            PunktyRelacje = 0,
                            PunktyUmysl = 0,
                            PytanieId = 8,
                            Tresc = "5"
                        },
                        new
                        {
                            Id = 40,
                            PunktyCialo = 0,
                            PunktyDuchowosc = 0,
                            PunktyPraca = 0,
                            PunktyRelacje = 10,
                            PunktyUmysl = 0,
                            PytanieId = 9,
                            Tresc = "Duszą towarzystwa"
                        },
                        new
                        {
                            Id = 41,
                            PunktyCialo = 0,
                            PunktyDuchowosc = 0,
                            PunktyPraca = 0,
                            PunktyRelacje = 8,
                            PunktyUmysl = 0,
                            PytanieId = 9,
                            Tresc = "Otwarty, ale spokojny"
                        },
                        new
                        {
                            Id = 42,
                            PunktyCialo = 0,
                            PunktyDuchowosc = 0,
                            PunktyPraca = 0,
                            PunktyRelacje = 0,
                            PunktyUmysl = 5,
                            PytanieId = 9,
                            Tresc = "Raczej obserwatorem"
                        },
                        new
                        {
                            Id = 43,
                            PunktyCialo = 0,
                            PunktyDuchowosc = 5,
                            PunktyPraca = 0,
                            PunktyRelacje = 0,
                            PunktyUmysl = 0,
                            PytanieId = 9,
                            Tresc = "Potrzebuję czasu żeby się otworzyć"
                        },
                        new
                        {
                            Id = 44,
                            PunktyCialo = 10,
                            PunktyDuchowosc = 0,
                            PunktyPraca = 0,
                            PunktyRelacje = 0,
                            PunktyUmysl = 0,
                            PytanieId = 10,
                            Tresc = "Sport / zdrowie"
                        },
                        new
                        {
                            Id = 45,
                            PunktyCialo = 0,
                            PunktyDuchowosc = 0,
                            PunktyPraca = 0,
                            PunktyRelacje = 0,
                            PunktyUmysl = 10,
                            PytanieId = 10,
                            Tresc = "Wiedza / nauka"
                        },
                        new
                        {
                            Id = 46,
                            PunktyCialo = 0,
                            PunktyDuchowosc = 0,
                            PunktyPraca = 0,
                            PunktyRelacje = 10,
                            PunktyUmysl = 0,
                            PytanieId = 10,
                            Tresc = "Relacje z ludźmi"
                        },
                        new
                        {
                            Id = 47,
                            PunktyCialo = 0,
                            PunktyDuchowosc = 0,
                            PunktyPraca = 10,
                            PunktyRelacje = 0,
                            PunktyUmysl = 0,
                            PytanieId = 10,
                            Tresc = "Kariera / umiejętności"
                        },
                        new
                        {
                            Id = 48,
                            PunktyCialo = 0,
                            PunktyDuchowosc = 10,
                            PunktyPraca = 0,
                            PunktyRelacje = 0,
                            PunktyUmysl = 0,
                            PytanieId = 10,
                            Tresc = "Rozwój wewnętrzny / spokój"
                        });
                });

            modelBuilder.Entity("zadanie4.Models.ProfilUzytkownika", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cialo")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Duchowosc")
                        .HasColumnType("int");

                    b.Property<int>("Praca")
                        .HasColumnType("int");

                    b.Property<int>("Relacje")
                        .HasColumnType("int");

                    b.Property<int>("Umysl")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Profile");
                });

            modelBuilder.Entity("zadanie4.Models.Pytanie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Tresc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Typ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pytania");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Tresc = "Co najczęściej robisz, kiedy masz wolną godzinę tylko dla siebie?",
                            Typ = "choice"
                        },
                        new
                        {
                            Id = 2,
                            Tresc = "Na ile lubisz wyzwania fizyczne? (sport, trening, aktywność)",
                            Typ = "scale"
                        },
                        new
                        {
                            Id = 3,
                            Tresc = "Czy często wpadają Ci do głowy nowe pomysły albo projekty?",
                            Typ = "scale"
                        },
                        new
                        {
                            Id = 4,
                            Tresc = "Co bardziej Cię napędza?",
                            Typ = "choice"
                        },
                        new
                        {
                            Id = 5,
                            Tresc = "Jak bardzo lubisz działać w grupie?",
                            Typ = "scale"
                        },
                        new
                        {
                            Id = 6,
                            Tresc = "Gdy masz problem, co robisz jako pierwsze?",
                            Typ = "choice"
                        },
                        new
                        {
                            Id = 7,
                            Tresc = "Czy dbasz o swoje zdrowie i energię? (sen, ruch, jedzenie)",
                            Typ = "scale"
                        },
                        new
                        {
                            Id = 8,
                            Tresc = "Jak ważny jest dla Ciebie rozwój osobisty?",
                            Typ = "scale"
                        },
                        new
                        {
                            Id = 9,
                            Tresc = "Kiedy poznajesz nowych ludzi, jesteś raczej:",
                            Typ = "choice"
                        },
                        new
                        {
                            Id = 10,
                            Tresc = "Gdybyś miał wybrać jedną rzecz, w której chcesz się najbardziej rozwijać?",
                            Typ = "choice"
                        });
                });

            modelBuilder.Entity("zadanie4.Models.Odpowiedz", b =>
                {
                    b.HasOne("zadanie4.Models.Pytanie", "Pytanie")
                        .WithMany("Odpowiedzi")
                        .HasForeignKey("PytanieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pytanie");
                });

            modelBuilder.Entity("zadanie4.Models.Pytanie", b =>
                {
                    b.Navigation("Odpowiedzi");
                });
#pragma warning restore 612, 618
        }
    }
}
